---
resource_types:
- name: registry-image
  type: docker-image
  source:
    repository: concourse/registry-image-resource
    tag: latest

resources:
- name: my-docker-image
  type: registry-image
  source:
    repository: my-image-repo
    tag: latest
    username: ((docker-username))
    password: ((docker-password))

jobs:
- name: my-job
  plan:
  - get: my-docker-image
    trigger: true
  - task: my-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: my-image-repo
          tag: latest
          username: ((docker-username))
          password: ((docker-password))
      run:
        path: my-script.sh
