---
groups:
- name: build-apps
  jobs:
  - job-1
  - job-3
- name: test-apps
  jobs:
  - job-2

jobs:
- name: job-1
  plan:
  - task: task1
    config:
        platform: linux
        image_resource:
            type: registry-image
            source:
                repository: maven
                tag: latest
        run:
          path: ls
- name: job-2
  plan:
  - task: task1
    config:
        platform: linux
        image_resource:
            type: registry-image
            source:
                repository: maven
                tag: latest
        run:
          path: time
- name: job-3
  plan:
  - task: task1
    config:
        platform: linux
        image_resource:
            type: registry-image
            source:
                repository: maven
                tag: latest
        run:
          path: pwd